## YAML Template.
---
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: false

server:
    port: 48152
    
custom:
    activeprofileName: prd
    
spring:
    application:
        name: customer
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    h2: 
        console:
            enabled: true
        